language: python

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - clang-3.6

sudo: required
dist: trusty

python:
  # - "2.7"
  # - "3.4"
  # - "3.5"
  - "3.6"

env:
  global:
    - COMPILER=clang++-3.6
    - CXX=clang++-3.6
    - CC=clang-3.6

compiler: clang

branches:
  only:
  - /.*/

install:
  - pip install pipenv codecov
  - pipenv run python setup.py build
  - pipenv run python setup.py bdist_egg
  - pipenv install --dev
script:
  - pipenv run pytest -x --doctest-modules --cov=sem/
  - codecov
